#!/usr/bin/env php
<?php

/**
 * Registers the Composer autoloader.
 */
require_once 'bootstrap/start.php';

/**
 * Strips all of the underscores within the
 * given string.
 *
 * @param  string $string
 * @return string
 */
function stripUnderscore($string) {
    $string[0] = strtoupper($string[0]);

    for ($i = 0; $i < strlen($string); $i++) {
        if ($string[$i] === '_') {
            $string[$i + 1] = strtoupper($string[$i + 1]);
        }
    }

    return str_replace('_', '', $string);
}

/**
 * Returns the migration class name.
 *
 * @param  string $migration
 * @return string
 */
function getMigrationClassName($migration) {
    $file = basename($migration);

    $class = stripUnderscore($file);

    return str_replace('.php', '', $class);
}

/**
 * Resolves all of the migrations with
 * a given method.
 *
 * @param  string $method
 * @return void
 */
function resolveMigrations($method) {
    $migrations = glob(__DIR__ . '/database/migrations/*.php');

    foreach ($migrations as $migration) {
        $class = getMigrationClassName($migration);

        (new $class)->$method();

        if ($method === 'up') {
            echo $class . ' migration was successful.' . PHP_EOL;
        } else {
            echo $class . ' migration was successfully reset.' . PHP_EOL;
        }
    }
}

/**
 * Handles the arguments received.
 */
switch ($argv[1]) {
    case 'migrate':
        resolveMigrations('up');
    break;
    case 'migrate:reset':
        resolveMigrations('down');
    break;
    case 'seed':
        (new DatabaseSeeder())->run();
    break;
    default:
        echo 'Slim does not recognize that command.';
    break;
}
